envGroups:
  - name: rotaract-shared-config
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://4084senthilnathan_db_user:APGXIlTcGnujDnfG@cluster0.msixys2.mongodb.net/rotaract_club?appName=Cluster0
      - key: JWT_SECRET
        value: RotaractClubofAIHT185693anandinsitituteofhighertechnology
      - key: CLOUDINARY_NAME
        value: dddohslgv
      - key: CLOUDINARY_API_KEY
        value: 164913897936228
      - key: CLOUDINARY_API_SECRET
        value: d2itDke45YIopjuMk6iMOkig-Rk
      - key: FRONTEND_URL
        value: https://rotaract-frontend.onrender.com
      - key: ALLOWED_ORIGINS
        value: http://localhost:3000,https://rotaract-frontend.onrender.com
      - key: NEXT_PUBLIC_API_URL
        value: https://rotaract-backend.onrender.com/api

services:
  # Backend Service
  - type: web
    name: rotaract-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - fromEnvGroup: rotaract-shared-config
      - key: NODE_ENV
        value: production

  # Frontend Service
  - type: web
    name: rotaract-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - fromEnvGroup: rotaract-shared-config
      - key: NODE_ENV
        value: production
